# Generated by Django 5.2 on 2025-04-09 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicianassignment',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_technicians', to='core.machine'),
        ),
        migrations.AlterField(
            model_name='technicianassignment',
            name='technician',
            field=models.ForeignKey(limit_choices_to={'user_type': 'technician'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_machines', to=settings.AUTH_USER_MODEL),
        ),
    ]
